version: "3.9"

services:
  server:
    build: .
    container_name: novo-server
    depends_on:
      - database
    environment:
      POSTGRES_URL: "postgres://root:root@database:5432/novo?sslmode=disable"
      VIRTUAL_HOST: "api.novoapp.tech"
      LETSENCRYPT_HOST: "api.novoapp.tech"
    ports:
      - "7001:8080"
    volumes:
      - data:/app/static/images
  database:
    image: postgres:14.0
    container_name: novo-database
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: novo
#      PGDATA: /var/lib/postgresql/data/sub/
    ports:
      - "5432:5432"
  sqlc:
    image: kjconroy/sqlc
    container_name: novo-sqlc
    volumes:
      - ./:/src
    working_dir: /src
    command: "generate"
  migrate:
    image: migrate/migrate
    container_name: novo-migrate
    depends_on:
      - database
    volumes:
      - ./static/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://root:root@database:5432/novo?sslmode=disable", "up" ]
  client:
    build: client
    container_name: novo-client
    environment:
      VIRTUAL_HOST: "novoapp.tech"
      LETSENCRYPT_HOST: "novoapp.tech"
    ports:
      - "7002:3000"

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - "nginx-proxy"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  data:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme:
